#ArcGIS Pro Modelbuilder, to convert raster file containing shoreline back to polyline

# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-12-20 14:20:51
"""
import arcpy
from sys import argv

#For inline variable substitution, parameters passed as a String are evaluated using locals(), globals() and isinstance(). To override, substitute values directly.
def GCPCorrection(Filename="WV_", Input_Raster_Band, Database):  # GCP Correction

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False


    # Process: Raster to Polygon (Raster to Polygon) (conversion)
    _Filename_R2P = fr"{Database}\{Filename}_R2P"
    arcpy.conversion.RasterToPolygon(in_raster=Input_Raster_Band.__str__().format(**locals(),**globals())if isinstance(Input_Raster_Band, str) else Input_Raster_Band, out_polygon_features=_Filename_R2P, simplify="NO_SIMPLIFY")

    # Process: Select (Select) (analysis)
    _Filename_R2P2 = fr"{Database}\{Filename}_R2P2"
    arcpy.analysis.Select(in_features=_Filename_R2P, out_feature_class=_Filename_R2P2, where_clause="gridcode <> 0")

    # Process: Pairwise Buffer (Pairwise Buffer) (analysis)
    _Filename_Buffer = fr"{Database}\{Filename}_Buffer"
    arcpy.analysis.PairwiseBuffer(in_features=_Filename_R2P2, out_feature_class=_Filename_Buffer, buffer_distance_or_field="0.01 Meters", dissolve_option="LIST", dissolve_field=["gridcode"], method="GEODESIC")

    # Process: Polygon To Line (Polygon To Line) (management)
    _Filename_Shoreline_nonsmooth = fr"{Database}\{Filename}_Shoreline_nonsmooth"
    arcpy.management.PolygonToLine(in_features=_Filename_Buffer, out_feature_class=_Filename_Shoreline_nonsmooth, neighbor_option="IDENTIFY_NEIGHBORS")

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="C:\\JessicaWorking\\Tuktoyaktuk\\Tuktoyaktuk Coastline Digitization\\Accumulation.gdb", workspace="C:\\JessicaWorking\\Tuktoyaktuk\\Tuktoyaktuk Coastline Digitization\\Accumulation.gdb"):
        GCPCorrection(*argv[1:])
